module Evergreen.Migrate.V5 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V2.BestScores.Types
import Evergreen.V2.Lives
import Evergreen.V2.Multiplication
import Evergreen.V2.NonEmpty
import Evergreen.V2.Types
import Evergreen.V5.BestScores.Types
import Evergreen.V5.Lives
import Evergreen.V5.Multiplication
import Evergreen.V5.NonEmpty
import Evergreen.V5.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V5.Types.FrontendModel Evergreen.V5.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V5.Types.BackendModel Evergreen.V5.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V5.Types.FrontendMsg Evergreen.V5.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V5.Types.ToBackend Evergreen.V5.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V5.Types.BackendMsg Evergreen.V5.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V5.Types.ToFrontend Evergreen.V5.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V2.Types.FrontendModel -> Evergreen.V5.Types.FrontendModel
migrate_Types_FrontendModel old =
    { page = old.page |> migrate_Types_Page
    , tables = old.tables |> migrate_NonEmpty_NonEmpty identity
    }


migrate_BestScores_Types_Model : Evergreen.V2.BestScores.Types.Model -> Evergreen.V5.BestScores.Types.Model
migrate_BestScores_Types_Model old =
    case old of
        Evergreen.V2.BestScores.Types.Loading ->
            Evergreen.V5.BestScores.Types.Loading

        Evergreen.V2.BestScores.Types.Loaded p0 ->
            Evergreen.V5.BestScores.Types.Loaded p0


migrate_BestScores_Types_Msg : Evergreen.V2.BestScores.Types.Msg -> Evergreen.V5.BestScores.Types.Msg
migrate_BestScores_Types_Msg old =
    case old of
        Evergreen.V2.BestScores.Types.GotScores p0 ->
            Evergreen.V5.BestScores.Types.GotScores p0


migrate_Lives_Model : Evergreen.V2.Lives.Model -> Evergreen.V5.Lives.Model
migrate_Lives_Model old =
    { state = old.state |> migrate_Lives_State
    , tables = old.tables |> migrate_NonEmpty_NonEmpty identity
    , answered = old.answered |> List.map (Tuple.mapFirst migrate_Multiplication_Multiplication)
    }


migrate_Lives_Msg : Evergreen.V2.Lives.Msg -> Evergreen.V5.Lives.Msg
migrate_Lives_Msg old =
    case old of
        Evergreen.V2.Lives.GotMultiplication p0 ->
            Evergreen.V5.Lives.GotMultiplication (p0 |> migrate_Multiplication_Multiplication)

        Evergreen.V2.Lives.Select p0 ->
            Evergreen.V5.Lives.Select p0

        Evergreen.V2.Lives.Next ->
            Evergreen.V5.Lives.Next

        Evergreen.V2.Lives.GotGameOverGif p0 ->
            Evergreen.V5.Lives.GotGameOverGif p0


migrate_Lives_PlayingState : Evergreen.V2.Lives.PlayingState -> Evergreen.V5.Lives.PlayingState
migrate_Lives_PlayingState old =
    case old of
        Evergreen.V2.Lives.Idle ->
            Evergreen.V5.Lives.Idle

        Evergreen.V2.Lives.Answered p0 ->
            Evergreen.V5.Lives.Answered { answer = p0, since = 0, wait = 0 }


migrate_Lives_State : Evergreen.V2.Lives.State -> Evergreen.V5.Lives.State
migrate_Lives_State old =
    case old of
        Evergreen.V2.Lives.Loading ->
            Evergreen.V5.Lives.Loading

        Evergreen.V2.Lives.Playing p0 p1 ->
            Evergreen.V5.Lives.Playing (p0 |> migrate_Lives_PlayingState)
                (p1 |> migrate_Multiplication_Multiplication)

        Evergreen.V2.Lives.GameOver p0 ->
            Evergreen.V5.Lives.GameOver p0


migrate_Multiplication_Multiplication : Evergreen.V2.Multiplication.Multiplication -> Evergreen.V5.Multiplication.Multiplication
migrate_Multiplication_Multiplication old =
    case old of
        Evergreen.V2.Multiplication.Multiplication p0 p1 p2 ->
            Evergreen.V5.Multiplication.Multiplication p0 p1 p2


migrate_NonEmpty_NonEmpty : (a_old -> a_new) -> Evergreen.V2.NonEmpty.NonEmpty a_old -> Evergreen.V5.NonEmpty.NonEmpty a_new
migrate_NonEmpty_NonEmpty migrate_a old =
    case old of
        Evergreen.V2.NonEmpty.NonEmpty p0 p1 ->
            Evergreen.V5.NonEmpty.NonEmpty (p0 |> migrate_a) (p1 |> List.map migrate_a)


migrate_Types_AgainstTheClockModel : Evergreen.V2.Types.AgainstTheClockModel -> Evergreen.V5.Types.AgainstTheClockModel
migrate_Types_AgainstTheClockModel old =
    { state = old.state |> migrate_Types_AgainstTheClockState
    , tables = old.tables |> migrate_NonEmpty_NonEmpty identity
    , score = old.score
    , remainingTime = old.remainingTime
    }


migrate_Types_AgainstTheClockMsg : Evergreen.V2.Types.AgainstTheClockMsg -> Evergreen.V5.Types.AgainstTheClockMsg
migrate_Types_AgainstTheClockMsg old =
    case old of
        Evergreen.V2.Types.GotMultiplication p0 ->
            Evergreen.V5.Types.GotMultiplication (p0 |> migrate_Multiplication_Multiplication)

        Evergreen.V2.Types.Select p0 ->
            Evergreen.V5.Types.Select p0

        Evergreen.V2.Types.Tick ->
            Evergreen.V5.Types.Tick

        Evergreen.V2.Types.DidInputPlayer p0 ->
            Evergreen.V5.Types.DidInputPlayer p0

        Evergreen.V2.Types.SubmitScore ->
            Evergreen.V5.Types.SubmitScore


migrate_Types_AgainstTheClockState : Evergreen.V2.Types.AgainstTheClockState -> Evergreen.V5.Types.AgainstTheClockState
migrate_Types_AgainstTheClockState old =
    case old of
        Evergreen.V2.Types.Loading ->
            Evergreen.V5.Types.Loading

        Evergreen.V2.Types.Playing p0 ->
            Evergreen.V5.Types.Playing (p0 |> migrate_Multiplication_Multiplication)

        Evergreen.V2.Types.GameOver p0 ->
            Evergreen.V5.Types.GameOver (p0 |> migrate_Types_GameOverState)


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V5.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V2.Types.LivesMsg p0 ->
            Evergreen.V5.Types.LivesMsg (p0 |> migrate_Lives_Msg)

        Evergreen.V2.Types.AgainstTheClockMsg p0 ->
            Evergreen.V5.Types.AgainstTheClockMsg (p0 |> migrate_Types_AgainstTheClockMsg)

        Evergreen.V2.Types.BestScoresMsg p0 ->
            Evergreen.V5.Types.BestScoresMsg (p0 |> migrate_BestScores_Types_Msg)

        Evergreen.V2.Types.ClickLives ->
            Evergreen.V5.Types.ClickLives

        Evergreen.V2.Types.ClickAgainstTheClock ->
            Evergreen.V5.Types.ClickAgainstTheClock

        Evergreen.V2.Types.ClickBestScores ->
            Evergreen.V5.Types.ClickBestScores

        Evergreen.V2.Types.RemoveTable p0 ->
            Evergreen.V5.Types.RemoveTable p0

        Evergreen.V2.Types.AddTable p0 ->
            Evergreen.V5.Types.AddTable p0

        Evergreen.V2.Types.ClickHome ->
            Evergreen.V5.Types.ClickHome

        Evergreen.V2.Types.UrlChanged p0 ->
            Evergreen.V5.Types.UrlChanged p0

        Evergreen.V2.Types.UrlClicked p0 ->
            Evergreen.V5.Types.UrlClicked p0


migrate_Types_GameOverState : Evergreen.V2.Types.GameOverState -> Evergreen.V5.Types.GameOverState
migrate_Types_GameOverState old =
    case old of
        Evergreen.V2.Types.Idle p0 ->
            Evergreen.V5.Types.Idle p0

        Evergreen.V2.Types.Submitting ->
            Evergreen.V5.Types.Submitting

        Evergreen.V2.Types.Submitted ->
            Evergreen.V5.Types.Submitted


migrate_Types_Page : Evergreen.V2.Types.Page -> Evergreen.V5.Types.Page
migrate_Types_Page old =
    case old of
        Evergreen.V2.Types.Home ->
            Evergreen.V5.Types.Home

        Evergreen.V2.Types.AgainstTheClock p0 ->
            Evergreen.V5.Types.AgainstTheClock (p0 |> migrate_Types_AgainstTheClockModel)

        Evergreen.V2.Types.Lives p0 ->
            Evergreen.V5.Types.Lives (p0 |> migrate_Lives_Model)

        Evergreen.V2.Types.BestScores p0 ->
            Evergreen.V5.Types.BestScores (p0 |> migrate_BestScores_Types_Model)
